image_processing:
  min_dimension_threshold: 800
  upscale_factor: 2
text_detection:
  bin_thresh: 0.3
  box_thresh: 0.1
shape_detection:
  verbose: true
  fill_circle_enclosing_threshold: 0.8
  fill_rect_enclosing_threshold: 0.95
  erosion_kernel_size:
  - 3
  - 3
  min_stable_length: 3
  max_erosion_iterations: 30
  classify_circle_overlap_threshold: 0.8
  classify_rect_overlap_threshold: 0.85
  remove_nodes_dilation_kernel_size:
  - 3
  - 3
  remove_nodes_dilation_iterations: 3
connection_processing:
  hough_rho: 1
  hough_theta_degrees: 1
  hough_threshold: 15
  hough_min_line_length: 10
  hough_max_line_gap: 25
  hough_bundler_min_distance: 10
  hough_bundler_min_angle: 3
  arrowhead_confidence_threshold_percent: 10
  proximity_thres_place: 1.5
  proximity_thres_trans_height: 1.4
  proximity_thres_trans_width: 3
  path_finding:
    proximity_threshold: 30
    dot_product_weight: 0.6
    distance_to_line_weight: 0.2
    endpoint_distance_weight: 0.2
  arrowhead_proximity_threshold: 40
  text_linking_threshold: 25
